"""ADK tools for the five AI agent services (Auditor, Recommender, Investigator, Coordinator, Isolator).

Each tool calls the corresponding Cloud Run service via HTTP.
These are READ-ONLY query tools safe to expose on the ADK chat surface.
"""

import json
import os

import httpx

AUDITOR_URL = os.environ.get("AUDITOR_REST_URL", "https://agent-auth-gateway-auditor-1031148889398.us-central1.run.app")
RECOMMENDER_URL = os.environ.get("RECOMMENDER_REST_URL", "https://agent-auth-gateway-recommender-1031148889398.us-central1.run.app")
INVESTIGATOR_URL = os.environ.get("INVESTIGATOR_REST_URL", "https://agent-auth-investigator-1031148889398.us-central1.run.app")
COORDINATOR_URL = os.environ.get("COORDINATOR_REST_URL", "https://agent-auth-gateway-coordinator-1031148889398.us-central1.run.app")
ISOLATOR_URL = os.environ.get("ISOLATOR_REST_URL", "https://agent-auth-isolator-1031148889398.us-central1.run.app")

_TIMEOUT = 30


async def _call(base: str, method: str, path: str, params: dict | None = None, body: dict | None = None) -> dict:
    async with httpx.AsyncClient(timeout=_TIMEOUT) as c:
        if method == "GET":
            r = await c.get(f"{base}{path}", params=params)
        else:
            r = await c.post(f"{base}{path}", json=body, params=params)
        r.raise_for_status()
        return r.json()


# --- Auditor tools ---

async def query_audit_reports(tenant: str = "hackathon-demo", limit: int = 20) -> str:
    """Query compliance audit reports. Each report has a verdict (ALIGNED, CONFLICT, INSUFFICIENT_EVIDENCE),
    rationale, and verbatim citations from OWASP, NIST AI RMF, and NIST SP 800-53."""
    result = await _call(AUDITOR_URL, "GET", "/audit-reports", params={"tenant": tenant, "limit": limit})
    return json.dumps(result, default=str)


async def audit_receipt(tenant: str, receipt_seq: int) -> str:
    """Trigger an on-demand compliance audit of a specific receipt. Uses Gemini 2.5 Pro + RAG
    to evaluate the authorization decision against OWASP and NIST frameworks. May take 10-30 seconds."""
    result = await _call(AUDITOR_URL, "POST", "/audit-receipt", body={"tenant": tenant, "receipt_seq": receipt_seq})
    return json.dumps(result, default=str)


async def get_auditor_keys() -> str:
    """Get the Auditor's Ed25519 public signing key."""
    result = await _call(AUDITOR_URL, "GET", "/audit-keys")
    return json.dumps(result, default=str)


# --- Recommender tools ---

async def query_policy_proposals(tenant: str = "hackathon-demo", limit: int = 20) -> str:
    """Query policy change proposals generated by the Recommender from CONFLICT pattern detection."""
    result = await _call(RECOMMENDER_URL, "GET", "/proposals", params={"tenant": tenant, "limit": limit})
    return json.dumps(result, default=str)


async def get_recommender_keys() -> str:
    """Get the Recommender's Ed25519 public signing key."""
    result = await _call(RECOMMENDER_URL, "GET", "/recommender-keys")
    return json.dumps(result, default=str)


# --- Investigator tools ---

async def query_incidents(tenant: str = "hackathon-demo", limit: int = 20) -> str:
    """Query incident reports assembled by the Investigator from CONFLICT-triggered evidence."""
    result = await _call(INVESTIGATOR_URL, "GET", "/incidents", params={"tenant": tenant, "limit": limit})
    return json.dumps(result, default=str)


async def get_investigator_keys() -> str:
    """Get the Investigator's Ed25519 public signing key."""
    result = await _call(INVESTIGATOR_URL, "GET", "/investigator-keys")
    return json.dumps(result, default=str)


# --- Coordinator tools ---

async def route_capability(question: str) -> str:
    """Ask the Coordinator which agent can handle a given capability question.
    Uses Gemini to match natural-language queries to registered A2A agents."""
    result = await _call(COORDINATOR_URL, "POST", "/route-question", body={"question": question})
    return json.dumps(result, default=str)


async def list_known_agents() -> str:
    """List all agents registered in the Coordinator's A2A directory."""
    result = await _call(COORDINATOR_URL, "GET", "/directory")
    return json.dumps(result, default=str)


async def get_coordinator_keys() -> str:
    """Get the Coordinator's Ed25519 public signing key."""
    result = await _call(COORDINATOR_URL, "GET", "/coordinator-keys")
    return json.dumps(result, default=str)


# --- Isolator tools ---

async def query_isolation_records(tenant: str = "hackathon-demo", limit: int = 20) -> str:
    """Query isolation records showing agents that were quarantined for rogue behavior."""
    result = await _call(ISOLATOR_URL, "GET", "/isolation-records", params={"tenant": tenant, "limit": limit})
    return json.dumps(result, default=str)


async def get_isolator_keys() -> str:
    """Get the Isolator's Ed25519 public signing key."""
    result = await _call(ISOLATOR_URL, "GET", "/isolator-keys")
    return json.dumps(result, default=str)
